id: 4438cf9e-4946-11ed-b878-0242ac120002
full_slug: virtual-private-servers-pre-installed-applications
disable_languages:
  - fr-ca

# For this guide, we do not want anything to be generated for fr-ca localization
